ImGoing/urls.py
from django.contrib import admin
from django.urls import path, include
import main.views
import blog.views
#import login.views
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.home, name='home'),
    path('main/', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
]

accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf.urls import include

app_name='blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('poast/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/<int:year>/',views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/',views.PostTAV.as_view(), name='post_today'),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf.urls import include



urlpatterns = [
    path('location/', views.location, name='location'), 
    path('write/', views.write, name='write'),
    path('account/', views.account, name='account'),
    path('create/', views.create, name='create'),
    path('newproduct/', views.productpost, name='newproduct'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=100)
    content = models.TextField('CONTENT', default='')
    pub_date = models.DateTimeField('PUBLISH DATE', default=timezone.now)
    mod_date = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name='post'
        verbose_name_plural='posts'
        db_table='blog_posts'
        ordering = ('-mod_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_mod_date()

    def get_next(self):
        return self.get_next_by_mod_date()

main/models.py
from django.db import models

class Market(models.Model):
    title = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    swap = models.CharField(max_length=100)
    price = models.IntegerField()
    content = models.TextField()
    file_route = models.CharField(max_length=100)
    tag = models.CharField(max_length=200)

class Product(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()

main/forms.py
from django import forms
from .models import Product

class ProductPost(forms.ModelForm):
    class Meta:
        model =  Product
        fields = ['title', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.


def signup(request):
    if request.method == 'POST':
        # User has info and wants an account now!
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'signup.html', {'error': 'Username has already been taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                auth.login(request, user)
                return redirect('blog')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords must match'})
    else:
        # User wants to enter info
        return render(request, 'signup.html')

def login(request):
    if request.method == 'POST':
				username = request.POST['username']
		    password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')
    return render(request, 'signup.html')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, TodayArchiveView, YearArchiveView, MonthArchiveView, DayArchiveView

from blog.models import Post

class PostLV(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 10

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'mod_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'mod_date'
    make_object_list=True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'mod_date'
    month_format = '%m'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'mod_date'
    month_format = '%m'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'mod_date'

#def post_list(request):
#    psots = Post.objects.all()
#    return render(request, 'blog/post_list.html', {'blog': posts})

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Market
from django.utils import timezone
from .forms import ProductPost



def home(request):
    return render(request, 'home.html')

def location(request):
    return render(request, 'location.html')

def write(request):
    return render(request, 'write.html')

def account(request):
    return render(request, 'account.html')

def create(request):
   product = Product()
   product.title = request.GET['title']
   product.body = request.GET['body']
   product.pub_date = timezone.datetime.now()
   product.save()
   return redirect('' + str(product.id))

def productpost(request):
    if request.method =='POST':
        form = ProductPost(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date=timezone.now()
            post.save()
            return redirect('location')
    else:
        form = ProductPost()
        return render(request,'product.html',{'form':form})

ImGoing/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>내가 가는 중이다</title>
    <style>
        body {
            font-family: "Apple SD Gothic Neo", "Malgun Gothic", 'Nanum Gothic', sans-serif;
            min-height: calc(100% - 77px);
            position: relative;
        }

       #fixed-bar{
           width: 100%;
           position: fixed;
           top: 0;
           right: 0;
           left: 0;
           z-index: 100;
           background-color: #ffffff;
       }
        #fixed-bar-wrap{
            width: 670px;
            margin: 0 auto;
            padding: 17px 0;
            position: relative;
        }

        .fixed-logo{
            width: 132px;
            vertical-align: text-bottom;
            margin-bottom: 5px;
        }

        #fixed-bar-search{
            position: absolute;
            left: 150px;
            top: 35px;
            border-radius: 4px;
            border: solid 1px #eb3b3b;
            text-decoration: none;
            padding: 1px 8px 1px 14px;
            height: 40px;
        }

        .search-input-wrap{
            position: relative;
            padding-right: 40px;
        }

        .login-input-wrap{
            position: relative;
            padding-right: 20px;
        }

        .sr-only{
            position: absolute;
            width: 1px;
            height: 1px;
            padding: 0;
            margin: -1px;
            overflow: hidden;
            clip: rect(0 0 0 0);
            border: 0;
        }

        .fixed-search-input{
            width: 440px;
            height: 38px;
            border: none;
            font-size: 18px;
            color: #212529;
            margin-right: 6px;
        }

        button{
            background: none;
            color: inherit;
            border: none;
            padding: 0;
            font: inherit;
            cursor: pointer;
            outline: inherit;
        }

        .fixed-search-icon{
            position: absolute;
            top: 0;
            right: 0;
            width: 26px;
            height: 26px;
            fill: #eb3b3b;
            padding: 7px 7px;
        }

        .fixed-bar-login{
            position: absolute;
            top: 0;
            right: 0;
            width: 26px;
            height: 26px;
            fill: #eb3b3b;
            padding: 7px 7px;
        }

        .header-login-button{
            width: 300px;
            height: 100px;
        }

        .fixed-login-icon{
            width: 60px;
            height: 20px;
        }

        .map{
            width: 980px;
            background-color: aqua;
            color: black;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <header id="fixed-bar">
        <div id="fixed-bar-wrap">
            <h1 id="fixed-bar-logo-title">
                <a href="{% url 'home' %}">
                    <span class="sr-only">내가 가는 중</span>
                    <img class="fixed-logo" src="https://d1unjqcospf8gs.cloudfront.net/assets/home/base/header/logo-basic-00b7e471b721ce9db8b0758c05a84684413c8aef1ad54caa0f3fcbe7328c947f.svg" alt="내가 가는 중" />
                </a>
            </h1>
            <section id="fixed-bar-search">
                <div class="search-input-wrap">
                    <span class="sr-only">검색</span>
                    <input type="text" name="header-search-input" id="header-search-input" class="fixed-search-input" placeholder="search yout location or products" />
                    <button id="header-search-button">
                        <img src="https://d1unjqcospf8gs.cloudfront.net/assets/home/base/header/search-icon-db20a2e9e6b0fc922b44982d451cf1c967c86e8e8df270e71c300832a6f31f1a.svg" alt="Search" class="fixed-search-icon" />
                    </button>
                </div>
            </section>
            <section id="fixed-bar-login">
                <div class="login-input-wrap">
                    <span class="sr-only">로그인</span>
                    <a href="{% url 'account' %}">
                        <img src="https://www.pngkey.com/png/full/245-2458169_facebook-login-button-google-login-button-google-login.png" alt="Search" class="fixed-login-icon" />
                        로그인
                    </a>
                    
                </div>
            </section>
        </div>
    </header>

   
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    
</body>
</html>

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Login</h1>

<form>
    Username:
    <br>
    <input name="username" type="text" value="">
    <br>
    Password:
    <br>
    <input name="password" type="password" value="">
    <br>
    <br>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

{% endblock %}

accounts/templates/signup.html
{% if error %}
{{ error }}
<br>
<br>
{% endif %}

<h1>Sign Up!</h1>

<form method="POST" action="{% url 'signup'%}">

{% csrf_token %}
Username:
<br>
<input name="username"  type="text" value="">
<br>
Password:
<br>
<input name="password1"  type="password" value="">
<br>
Confirm Password:
<br>
<input name="password2"  type="password" value="">
<br>
<br>
<input class="btn btn-primary" type="submit" value="Sign Up!">
</form>

{% endblock %}

blog/templates/blog/post_detail.html
<p><strong>{{object.title}}</strong></p>


<p>{{object.mod_date|date:"j F Y"  }}</p>  
<div>
    {{object.content|linebreaks}}
</div>
<br>
<br>
<p>
    {% if object.get_previous %}
    <a href="{{object.get_previous.get_absolute_url}}" title="이전글">&larr; {{object.get_previous}}</a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{object.get_next.get_absolute_url}} " title="다음글">{{object.get_next}} &rarr;</a>
    {% endif %}
</p>
<br>

<div>
    <button>요청 수락</button>
</div>
<br>
<br>
<div>
    <a href="{% url 'blog:post_list' %}">글목록</a>
    
</div>

</div>

blog/templates/blog/post_list.html
<style>
    .table_table-boardered{
        border-collapse: collapse;
        text-align: center;
        line-height: 1.5;
        border-top: 1px solid #ccc;
        border-left: 3px solid #369;
        margin: 20px 10px;
        

    }

    .table_table-boardered th{
        padding: 10px;
        font-weight: bold;
        vertical-align: top;
        color: #153d73;
        border-right: 1px solid #ccc;
        border-bottom: 1px solid #ccc;
    }

    .table_table-boardered td{
        padding: 10px;
        vertical-align: top;
        border-right: 1px solid #ccc;
        border-bottom: 1px solid #ccc;
    }
</style>


<h2>배달 의뢰 페이지</h2>

<div class="container">
    <table class="table_table-boardered">
        <tbody>
            <tr>
                <th style="width: 50px;">목록</th>
                <th style="width: 200px;">제목</th>
                <th style="width: 700px;">내용</th>
                <th style="width: 150px;">시간</th>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{post.id}}</td>
                <td> <h3><a href="{{post.get_absolute_url}}" style="text-decoration:none; color: rgb(62, 88, 160);">{{post.title}}</a></h3></td>
                <td>{{post.content}}</td>
                <td>{{post.mod_date|date:"N d, Y"}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!--
    {% for post in posts %}
<p>
    
    <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
    {{post.mod_date|date:"N d, Y"}}
    {% endfor %}
</p>
-->
<br>
<div>
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">이전페이지</a>
    {% endif %}

    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">다음페이지</a>
    {% endif %}
</div>

</div>

main/templates/account.html
{% load socialaccount %}
{% providers_media_js %}

<h1>hell world!</h1>

<a href="/accounts/signup">회원가입</a><br>

{% if user.is_authenticated %}
<a href="/accounts/logout">로그아웃</a><br>
{{user.username}} 님이 로그인 중

{% else %}
<a href="{% provider_login_url 'google' %}">구글 로그인</a><br>
당신 로그인 해야댐

{% endif %}

main/templates/home.html
{% extends 'base.html' %}

<div class="container">
{% block content %}

<style>
  #header-top{
  position: relative;
  background-color: #ffe6e3;
  color: #212529;
  }

  #header-title-wrap{
      position: relative;
      width: 980px;
      margin: 0 auto;
      padding-top: 200px;
      padding-bottom: 431px;
  }

  #header-title{
      text-align: center;
      font-size: 40px;
      font-weight: 600;
      line-height: 1.35;
      letter-spacing: -0.6px;
  }

  #header-title-desc{
      text-align: center;
      margin-top: 8px;
      font-size: 17px;
      line-height: 1.6;
      letter-spacing: -0.6px;
  }

  #hot-articles{
      position: relative;
      z-index: 1;
      background-color: white;
      padding: 120px 0;
  }

  h3{
      text-align: center;
  }

  .title-line-divider{
      width: 95px;
      border-top: 2px solid #eb3b3b;
      margin: 0 auto;
      margin-bottom: 50px;
  }

  .cards-wrap{
      width: 980px;
      margin: auto;
      text-align: center;
  }
  .card-top{
      position: relative;
      text-align: left;
      display: inline-block;
      border-radius: 8px;
      border: 1px solid #e9ecef;
      width: calc(25% - 34px);
      margin-left: 15px;
      margin-bottom: 40px;
  }
  .card-link{
      text-decoration: none;
      color: #212529;
  }

  .card-photo{
      width: 100%;
      position: relative;
      height: 160px;
      overflow: hidden;
      border-radius: 8px 8px 0 0;
      background-color: #f8f9fa;
  }

  .card-desc{
      padding: 16px;
      padding-bottom: 0;
  }

  .card-title{
      font-size: 17px;
      font-weight: 600;
      letter-spacing: -0.6px;
      color: #212529;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      margin-bottom: 6px;
      line-height: 1.2;
  }

  .card-region-name{
      font-size: 15px;
      color: #868e96;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      margin-bottom: 8px;
      line-height: 1.3;
  }

  .card-price{
      font-size: 15px;
      font-weight: 600;
      padding-bottom: 8px;
      border-bottom: 1px solid #e9ecef;
      line-height: 1.3;
      color: #eb3b3b;
  }

  #town-banner{
      text-align: left;
      padding: 48px 0;
      background-color: #f1bbb4;
  }

  #town-banner-wrap{
      position: relative;
      width: 980px;
      margin: 0 auto;
  }

  .town-logo{
      width: 154px;
      display: block;
      margin-bottom: 10px;
  }

  .town-banner-desc{
      columns: #212529;
      font-size: 24px;
      font-weight: 700;
      line-height: 1.6;
      margin-bottom: 12px;
  }

  .town-link-button{
      display: block;
      text-align: center;
      background-color: #eb3b3b;
      width: 240px;
      padding: 14px 0;
      font-size: 18px;
      font-weight: 600;
      color: white;
      text-decoration: none;
      border-radius: 6px;
  }

  .town-illust{
      position: absolute;
      bottom: 8px;
      right: 30px;
      width: 322px;
  }

</style>

<!--지도 API 받아옴-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=qkakh5h748"></script>
</head>

<section id="map">
  <div id="location" style="width: 100%; height: 400px;"></div>
</section>

 

<script>

  var map = new naver.maps.Map('map', {
  center: new naver.maps.LatLng(35.968469,126.957880),
  zoom: 18
  });

  var marker = new naver.maps.Marker({
      position: new naver.maps.LatLng(35.968469,126.957880),
      map: map
  });

</script>

<section id="header-top">
    <div id="header-title-wrap">
        <h1 id="header-title">Going To U</h1>
        <p id="header-title-desc">
            판매자, 구매자, 중간 거래를 도와주는 배달과 함께 거래를 경험해보세요.
        </p>
        <div id="header-image"></div>
    </div>
</section>

<section id="hot-articles">
    <h3>인기 상품</h3>
     <div class="title-line-divider"></div>
       <section class="cards-wrap">
         <article class="card-top ">
     <a class="card-link " data-event-label="103529666" href="/articles/103529666">
       <div class="card-photo">
           <img alt="캠핑용품 정리 합니다." src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/9f8b8e2a104950b91c32f39567ebb4d6c126bf6ad5dd41e3e27cfea530ff82bb.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">~~팝니다</h2>
         <div class="card-region-name">
           지역 이름
         </div>
         <div class="card-price ">
           가격
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103540056" href="/articles/103540056">
       <div class="card-photo">
           <img alt="ort 1단계 ~9단계" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/2f3ae553a8519d3bf58dbeaf6a7fa653c61d4255462eed9028964cb74ea3dd6e.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">ort 1단계 ~9단계</h2>
         <div class="card-region-name">
           대구 수성구 범어2동
         </div>
         <div class="card-price ">
           55,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103653052" href="/articles/103653052">
       <div class="card-photo">
           <img alt="제습기" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/91a29ad2e0374b5f27c14d5c123943450d6c23062e898a770b13259b734f9121.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">제습기</h2>
         <div class="card-region-name">
           부산 영도구 대평동1가
         </div>
         <div class="card-price ">
           30,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103616701" href="/articles/103616701">
       <div class="card-photo">
           <img alt="급))한샘 철제 선반" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/EBC92E2DB95E35BDA6E287205966A63C1112FE81E4BDB7BB79CE3E8327B0231F.jpg?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">급))한샘 철제 선반</h2>
         <div class="card-region-name">
           서울 강서구 가양제1동
         </div>
         <div class="card-price ">
           5,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103602293" href="/articles/103602293">
       <div class="card-photo">
           <img alt="제습기 팔아요" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/a66ca82562928fc07810fe69cad59a2a72854df63b3a8af6ae28590acb895f06.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">제습기 팔아요</h2>
         <div class="card-region-name">
           전북 전주시 완산구 효자4동
         </div>
         <div class="card-price ">
           50,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103643355" href="/articles/103643355">
       <div class="card-photo">
           <img alt="LG디오스 냉장고 팝니다." src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/863b9468a4053f17d30fcffc8c90014004a521042b613108720fe7b161d713a9.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">LG디오스 냉장고 팝니다.</h2>
         <div class="card-region-name">
           서울 강남구 삼성2동
         </div>
         <div class="card-price ">
           40,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103633325" href="/articles/103633325">
       <div class="card-photo">
           <img alt="딱딱한 복숭아" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/e86d71f5c7c9e050a8a08138e7ed75a65c082f125cd79f2d7545da433c09778a.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">딱딱한 복숭아</h2>
         <div class="card-region-name">
           세종시  고운동
         </div>
         <div class="card-price ">
           10,000원
         </div>
       </div>
   </a></article><article class="card-top ">
     <a class="card-link " data-event-label="103651830" href="/articles/103651830">
       <div class="card-photo">
           <img alt="자전거" src="https://dnvefa72aowie.cloudfront.net/origin/article/202007/dca779e8d022aaedea30adf26e048607d0505b63d98b2aadb6a23369089db512.webp?q=82&amp;s=300x300&amp;t=crop" />
       </div>
       <div class="card-desc">
         <h2 class="card-title">자전거</h2>
         <div class="card-region-name">
           서울 송파구 잠실3동
         </div>
         <div class="card-price ">
           30,000원
         </div>
       </div>
   </a></article>
       </section>

<section id="town-banner">
    <div id="town-banner-wrap">
        <img src="https://d1unjqcospf8gs.cloudfront.net/assets/home/landing/town-logo-7776f08e2d29692c029c4822ae909a8a96994612311f429473830632fa7c5657.svg" alt="town-logo" class="town-logo" />
        <p class="town-banner-desc">
            내 근처 상품은 이곳에서 찾아보세요.
        </p>
        <a href="{% url 'location' %}" target="_blank" id="town-link-button" class="town-link-button" data-event-category="town_link_from" data-event-action="index_base" data-event-label="town_banner">주변 가게 바로가기</a>
        <img src="https://d1unjqcospf8gs.cloudfront.net/assets/home/landing/town-illust-37d5e6189feda23581cd5fd7b238c1eb3734b0f99d846f46cfc66fb5384e6eb6.png" alt="town-illust" class="town-illust" />
    </div>
</section>
{% endblock %}

</div>

main/templates/product.html
<br>

<div class='container'>
    <form method='POST'>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <br>
        <input class="btn btn-dark" type="submit" value="제출하기">
    </form>
</div>